import { usePersonalityStore } from '~/stores/personality'
import type { AgentConfig } from '~/types/personality'

export function useExport() {
  const store = usePersonalityStore()

  const complexity = computed(() => {
    let c = 5 // Core personality (5 traits)
    c += store.communication.modifiers.length
    c += store.expertise.industries.length
    c += store.expertise.thinkingStyles.length
    c += store.expertise.learningApproach.length
    c += store.behavioral.errorHandling.length
    c += store.behavioral.adaptationBehavior.length
    c += store.behavioral.interactionPatterns.length
    c += store.advanced.technicalCapabilities.length
    c += store.advanced.conditionalBehaviors.length
    return c
  })

  function downloadFile(content: string, filename: string, type: string) {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  function exportFullConfig() {
    const agentConfig: AgentConfig = {
      version: '2.0',
      metadata: {
        name: 'Custom Agent',
        description: 'AI Agent created with Agent Crafter v2.0',
        createdAt: new Date().toISOString(),
        budgetUsed: store.budgetUsed,
        complexity: complexity.value,
      },
      core: { ...store.core },
      communication: {
        ...store.communication,
        modifiers: [...store.communication.modifiers],
        tones: { ...store.communication.tones },
      },
      expertise: {
        ...store.expertise,
        industries: [...store.expertise.industries],
        thinkingStyles: [...store.expertise.thinkingStyles],
        problemSolving: { ...store.expertise.problemSolving },
        learningApproach: [...store.expertise.learningApproach],
      },
      behavioral: {
        ...store.behavioral,
        errorHandling: [...store.behavioral.errorHandling],
        responseBehavior: { ...store.behavioral.responseBehavior },
        adaptationBehavior: [...store.behavioral.adaptationBehavior],
        interactionPatterns: [...store.behavioral.interactionPatterns],
      },
      advanced: {
        ...store.advanced,
        technicalCapabilities: [...store.advanced.technicalCapabilities],
        contentFilters: [...store.advanced.contentFilters],
        conditionalBehaviors: [...store.advanced.conditionalBehaviors],
        timeBehaviors: [...store.advanced.timeBehaviors],
      },
      facets: { ...store.facets },
    }

    downloadFile(JSON.stringify(agentConfig, null, 2), 'agent-crafter-v2-config.json', 'application/json')
  }

  function generatePromptTemplate(): string {
    return `# AI Agent Personality Configuration

## Core Personality
Extraversion: ${store.core.extraversion}/100
Agreeableness: ${store.core.agreeableness}/100
Conscientiousness: ${store.core.conscientiousness}/100
Emotional Stability: ${store.core.emotionalStability}/100
Openness: ${store.core.openness}/100

## Communication Style
Primary Style: ${store.communication.primaryStyle}
Modifiers: ${store.communication.modifiers.join(', ')}
Verbosity: ${store.communication.verbosity}/10
Structure: ${store.communication.structure}

## Professional Context
Expertise Level: ${store.expertise.level}
Role Archetype: ${store.expertise.roleArchetype}
Industries: ${store.expertise.industries.join(', ')}

## Behavioral Patterns
Proactivity: ${store.behavioral.proactivity}/100
Questioning Style: ${store.behavioral.questioningStyle}

## Custom Instructions
${store.advanced.systemInstructions}

---
Generated by Agent Crafter v2.0`
  }

  function exportPromptOnly() {
    downloadFile(generatePromptTemplate(), 'agent-prompt-template.txt', 'text/plain')
  }

  function generateAgentSummary(): string {
    const extLevel = store.core.extraversion > 60 ? 'high' : store.core.extraversion < 40 ? 'low' : 'moderate'
    return `# Agent Configuration Summary

**Generated:** ${new Date().toLocaleDateString()}
**Configuration Version:** 2.0

## Personality Overview
This agent combines ${extLevel} extraversion with ${store.communication.primaryStyle} communication style.

## Key Characteristics
- **Expertise:** ${store.expertise.level} level ${store.expertise.roleArchetype}
- **Communication:** ${store.communication.verbosity}/10 verbosity, ${store.communication.modifiers.length} style modifiers
- **Proactivity:** ${store.behavioral.proactivity}/100
- **Capabilities:** ${store.advanced.technicalCapabilities.length} technical capabilities

## Configuration Complexity
**Total Parameters Configured:** ${complexity.value}
**Budget Usage:** ${store.budgetUsed}/${store.budgetTotal}

## Notable Features
${store.advanced.systemInstructions ? '- Custom system instructions defined' : ''}
${store.behavioral.interactionPatterns.length > 0 ? `- ${store.behavioral.interactionPatterns.length} interaction patterns enabled` : ''}
${store.expertise.industries.length > 0 ? `- Specialized in ${store.expertise.industries.length} industries` : ''}

---
*Created with Agent Crafter v2.0*`
  }

  function exportSummary() {
    downloadFile(generateAgentSummary(), 'agent-summary-report.md', 'text/markdown')
  }

  async function importConfig(file: File): Promise<{ success: boolean; message: string }> {
    return new Promise((resolve) => {
      const reader = new FileReader()
      reader.onload = (e) => {
        try {
          const config = JSON.parse(e.target?.result as string)
          if (config.version === '2.0') {
            store.loadConfig(config)
            resolve({ success: true, message: 'Configuration imported successfully!' })
          } else {
            resolve({ success: false, message: 'Unsupported configuration version. Please use Agent Crafter v2.0 configurations.' })
          }
        } catch {
          resolve({ success: false, message: 'Invalid configuration file. Please check the JSON format.' })
        }
      }
      reader.readAsText(file)
    })
  }

  return {
    complexity,
    exportFullConfig,
    exportPromptOnly,
    exportSummary,
    importConfig,
  }
}
